### ISSUE TITLE
Incorrect mask on 18-bit mode

### ISSUE THREAD

**Issue by xobs** [FelipeCalliari/MMC5983MA#1]
It looks like this mask is incorrect:

https://github.com/FelipeCalliari/MMC5983MA/blob/a52a16b138962f134b90a6dcf614493e1cea15ab/src/MMC5983MA/MMC5983MA.py#L334

The bottom bits should be masked by 0x3, not 0x2. Right now I think it's missing the LSB.

**Comment by FelipeCalliari** [comment]
You are right, I will fix this. Thanks

**Comment by FelipeCalliari** [comment]
Fixed on #[66b23b9](https://github.com/FelipeCalliari/MMC5983MA/commit/66b23b9cca32ccae8060f598586b6ca40d75093e)
